variable "AZ" {}
variable "DEFAULT_ROUTE_TABLE_ID" {}
variable "DEFAULT_VPC_CIDR" {}
variable "DEFAULT_VPC_ID" {}
variable "ENV" {}
variable "PRIVATE_HOSTED_ZONE_ID" {}
variable "PUBLIC_SUBNETS" {}
variable "PRIVATE_SUBNETS" {}
variable "VPC_CIDR" {}
variable "PUBLIC_HOSTED_ZONE_ID" {}
